services:
  - type: web
    name: django-gbooking
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn gbooking.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gbooking.settings
      - key: SECRET_KEY
        value: your-secret-key