# Generated by Django 5.1.4 on 2025-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_userlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("Available", "Available"), ("CONFIRMED", "Confirmed")],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
