# Generated by Django 5.1.4 on 2025-06-18 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="children_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="food_times",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "Personal"),
                    ("guest", "Guest"),
                    ("other", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="booking_proofs/"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
